console.log("code1")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("code2")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")
console.log("new code ")